package com.revayato.app;
import static com.revayato.app.Theme.*;

import android.app.*;import android.content.*;import android.content.res.Configuration;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.*;import android.media.AudioManager;import android.net.Uri;import android.os.*;import android.provider.OpenableColumns;import android.util.Rational;import android.view.*;import android.widget.*;
import androidx.media3.common.*;import androidx.media3.datasource.*;import androidx.media3.exoplayer.*;import androidx.media3.exoplayer.source.DefaultMediaSourceFactory;import androidx.media3.exoplayer.upstream.DefaultAllocator;import androidx.media3.ui.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

/** Revayato cinematic player with touch gestures, subtitles, PiP and resume. */
@androidx.annotation.OptIn(markerClass = androidx.media3.common.util.UnstableApi.class)
public final class PlayerActivity extends Activity{
 static final int PICK_SUBTITLE=701,BG=0xff050706,LIME=0xffd8ff3e;static final String API=Config.API_BASE;final ExecutorService network=Executors.newSingleThreadExecutor();final Handler handler=new Handler(Looper.getMainLooper());final ArrayList<String> sources=new ArrayList<>();ExoPlayer player;PlayerView playerView;FrameLayout root,gestureLayer;LinearLayout toolbar;TextView feedback,titleView,sourceBadge;Button lockButton;GestureDetector gestures;AudioManager audio;String url,key,tracks;Uri imported;long position,startupAnchor;boolean playWhenReady=true,locked=false,sourceReady=false;int resizeIndex=0,sourceIndex=0,blips=0;float brightness=-1f;String wpCode="";boolean wpHost,wpApplying;WatchPartySocket wp;boolean reconcilingParty=false;final int[] resizeModes={AspectRatioFrameLayout.RESIZE_MODE_FIT,AspectRatioFrameLayout.RESIZE_MODE_ZOOM,AspectRatioFrameLayout.RESIZE_MODE_FILL};final String[] resizeLabels={"اندازه مناسب","برش سینمایی","تمام صفحه"};
  @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().setStatusBarColor(Color.BLACK);setVolumeControlStream(AudioManager.STREAM_MUSIC);immersive();url=safe(getIntent().getStringExtra("url"));tracks=safe(getIntent().getStringExtra("subtitles"));readSources();key="resume:"+Integer.toHexString((sources.isEmpty()?url:sources.get(0)).hashCode());position=state!=null?state.getLong("position"):getPreferences(0).getLong(key,0);if(state!=null&&!safe(state.getString("imported")).isEmpty())imported=Uri.parse(state.getString("imported"));audio=(AudioManager)getSystemService(AUDIO_SERVICE);wpCode=safe(getIntent().getStringExtra("watch_party_code"));wpHost=getIntent().getBooleanExtra("watch_party_host",false);buildUi();buildGestures();if(!hasTracks())reportMissing();}
 void buildUi(){root=new FrameLayout(this);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setBackgroundColor(Color.BLACK);playerView=new PlayerView(this);playerView.setShowBuffering(PlayerView.SHOW_BUFFERING_ALWAYS);playerView.setControllerShowTimeoutMs(4200);playerView.setControllerAutoShow(true);playerView.setKeepContentOnPlayerReset(true);playerView.setResizeMode(resizeModes[0]);root.addView(playerView,new FrameLayout.LayoutParams(-1,-1));gestureLayer=playerView;feedback=new TextView(this);feedback.setTextColor(Color.WHITE);feedback.setTextSize(17);feedback.setGravity(Gravity.CENTER);feedback.setPadding(dp(18),dp(10),dp(18),dp(10));GradientDrawable feedbackBg=pill(0xe6101512,18);feedbackBg.setStroke(dp(1),0x66d8ff3e);feedback.setBackground(feedbackBg);feedback.setVisibility(View.GONE);FrameLayout.LayoutParams fp=new FrameLayout.LayoutParams(-2,dp(52),Gravity.CENTER);root.addView(feedback,fp);sourceBadge=new TextView(this);sourceBadge.setTextColor(0xffd8ff3e);sourceBadge.setTextSize(11);sourceBadge.setGravity(Gravity.CENTER);sourceBadge.setPadding(dp(12),0,dp(12),0);GradientDrawable badgeBg=pill(0xaa101512,14);badgeBg.setStroke(dp(1),0x55d8ff3e);sourceBadge.setBackground(badgeBg);sourceBadge.setText(sourceLabel());FrameLayout.LayoutParams badgeLp=new FrameLayout.LayoutParams(-2,dp(34),Gravity.TOP|Gravity.END);badgeLp.setMargins(dp(14),dp(76),dp(14),dp(14));root.addView(sourceBadge,badgeLp);buildToolbar();setContentView(root);if(!getPreferences(0).getBoolean("gesture_help_seen",false)){handler.postDelayed(()->{showFeedback("دوبار لمس: ۱۰ ثانیه جلو/عقب  •  کشیدن عمودی: صدا و نور");getPreferences(0).edit().putBoolean("gesture_help_seen",true).apply();},700);}}
 void buildToolbar(){toolbar=new LinearLayout(this);toolbar.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);toolbar.setGravity(Gravity.CENTER_VERTICAL);toolbar.setPadding(dp(10),dp(8),dp(10),dp(8));toolbar.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0xdd000000,0x00000000}));Button back=control(R.drawable.ic_back,"بازگشت");back.setOnClickListener(v->finish());toolbar.addView(back,new LinearLayout.LayoutParams(dp(50),dp(50)));titleView=new TextView(this);titleView.setText(safe(getIntent().getStringExtra("title")));titleView.setTextColor(Color.WHITE);titleView.setTextSize(15);titleView.setTypeface(null,Typeface.BOLD);titleView.setSingleLine();titleView.setEllipsize(android.text.TextUtils.TruncateAt.END);titleView.setPadding(dp(10),0,dp(10),0);toolbar.addView(titleView,new LinearLayout.LayoutParams(0,dp(50),1));Button subtitle=control(R.drawable.ic_subtitle,"افزودن زیرنویس");subtitle.setOnClickListener(v->chooseSubtitle());toolbar.addView(subtitle,new LinearLayout.LayoutParams(dp(50),dp(50)));Button speed=control(R.drawable.ic_speed,"سرعت پخش");speed.setOnClickListener(v->speedDialog());toolbar.addView(speed,new LinearLayout.LayoutParams(dp(50),dp(50)));Button aspect=control(R.drawable.ic_aspect,"نسبت تصویر");aspect.setOnClickListener(v->cycleAspect());toolbar.addView(aspect,new LinearLayout.LayoutParams(dp(50),dp(50)));if(Build.VERSION.SDK_INT>=26){Button pip=control(R.drawable.ic_pip,"تصویر در تصویر");pip.setOnClickListener(v->enterPip());toolbar.addView(pip,new LinearLayout.LayoutParams(dp(50),dp(50)));}lockButton=control(R.drawable.ic_lock,"قفل کنترل‌ها");lockButton.setOnClickListener(v->toggleLock());toolbar.addView(lockButton,new LinearLayout.LayoutParams(dp(50),dp(50)));root.addView(toolbar,new FrameLayout.LayoutParams(-1,dp(68),Gravity.TOP));scheduleHide();}
 Button control(int icon,String description){Button b=new Button(this);b.setContentDescription(description);GradientDrawable bg=pill(0xdd151c18,18);bg.setStroke(dp(1),0x99a9c8b2);b.setBackground(new RippleDrawable(android.content.res.ColorStateList.valueOf(0x55d8ff3e),bg,null));b.setCompoundDrawablesWithIntrinsicBounds(icon,0,0,0);b.setPadding(dp(13),0,dp(13),0);b.setMinWidth(0);b.setMinHeight(0);b.setElevation(dp(5));b.setStateListAnimator(null);b.setOnFocusChangeListener((v,focused)->v.animate().scaleX(focused?1.1f:1f).scaleY(focused?1.1f:1f).setDuration(DUR_FAST).start());return b;}

 void buildGestures(){gestures=new GestureDetector(this,new GestureDetector.SimpleOnGestureListener(){@Override public boolean onDown(MotionEvent e){showControls();return true;}@Override public boolean onSingleTapConfirmed(MotionEvent e){if(locked){showToolbar(true);return true;}if(playerView.isControllerFullyVisible()){playerView.hideController();showToolbar(false);}else{playerView.showController();showToolbar(true);scheduleHide();}return true;}@Override public boolean onDoubleTap(MotionEvent e){if(locked||player==null)return true;long delta=e.getX()<root.getWidth()/2f?-10000:10000;player.seekTo(Math.max(0,Math.min(player.getDuration()>0?player.getDuration():Long.MAX_VALUE,player.getCurrentPosition()+delta)));if(wpHost)emitPartyPlayback();showFeedback(delta<0?"۱۰ ثانیه عقب":"۱۰ ثانیه جلو");return true;}@Override public boolean onScroll(MotionEvent start,MotionEvent now,float dx,float dy){if(locked||Math.abs(dy)<Math.abs(dx)||root.getHeight()==0)return true;float fraction=-dy/root.getHeight();if(start.getX()<root.getWidth()/2f)adjustBrightness(fraction);else adjustVolume(fraction);return true;}});gestureLayer.setOnTouchListener((v,e)->gestures.onTouchEvent(e));}
 void adjustBrightness(float amount){WindowManager.LayoutParams p=getWindow().getAttributes();float current=brightness>=0?brightness:(p.screenBrightness>=0?p.screenBrightness:.5f);brightness=Math.max(.02f,Math.min(1f,current+amount));p.screenBrightness=brightness;getWindow().setAttributes(p);showFeedback("روشنایی  "+Math.round(brightness*100)+"٪");}
 void adjustVolume(float amount){int max=audio.getStreamMaxVolume(AudioManager.STREAM_MUSIC),current=audio.getStreamVolume(AudioManager.STREAM_MUSIC);int value=Math.max(0,Math.min(max,current+Math.round(amount*max)));audio.setStreamVolume(AudioManager.STREAM_MUSIC,value,0);showFeedback("صدا  "+Math.round(value*100f/max)+"٪");}
 void showFeedback(String message){feedback.setText(message);feedback.setVisibility(View.VISIBLE);handler.removeCallbacks(hideFeedback);handler.postDelayed(hideFeedback,850);}final Runnable hideFeedback=()->feedback.setVisibility(View.GONE);
 void showControls(){if(!locked)showToolbar(true);scheduleHide();}void scheduleHide(){handler.removeCallbacks(hideChrome);handler.postDelayed(hideChrome,4300);}final Runnable hideChrome=()->{if(!locked&&!playerView.isControllerFullyVisible())showToolbar(false);};void showToolbar(boolean show){toolbar.setVisibility(show?View.VISIBLE:View.GONE);if(locked){toolbar.setVisibility(View.VISIBLE);for(int i=0;i<toolbar.getChildCount();i++)toolbar.getChildAt(i).setVisibility(toolbar.getChildAt(i)==lockButton?View.VISIBLE:View.GONE);}}
 void toggleLock(){locked=!locked;playerView.setUseController(!locked);gestureLayer.setContentDescription(locked?"کنترل‌ها قفل هستند؛ برای باز کردن لمس کنید":"سطح کنترل پخش");Toast.makeText(this,locked?"کنترل‌ها قفل شد":"قفل باز شد",Toast.LENGTH_SHORT).show();if(!locked){for(int i=0;i<toolbar.getChildCount();i++)toolbar.getChildAt(i).setVisibility(View.VISIBLE);playerView.showController();scheduleHide();}else showToolbar(true);}
 void cycleAspect(){resizeIndex=(resizeIndex+1)%resizeModes.length;playerView.setResizeMode(resizeModes[resizeIndex]);showFeedback(resizeLabels[resizeIndex]);}
 void speedDialog(){if(player==null)return;String[] labels={"۰٫۵×","۰٫۷۵×","عادی ۱×","۱٫۲۵×","۱٫۵×","۱٫۷۵×","۲×"};float[] values={.5f,.75f,1f,1.25f,1.5f,1.75f,2f};new AlertDialog.Builder(this).setTitle("سرعت پخش").setSingleChoiceItems(labels,nearestSpeed(values,player.getPlaybackParameters().speed),(d,w)->{player.setPlaybackSpeed(values[w]);d.dismiss();showFeedback(labels[w]);}).setNegativeButton("بستن",null).show();}int nearestSpeed(float[] values,float current){int best=0;for(int i=1;i<values.length;i++)if(Math.abs(values[i]-current)<Math.abs(values[best]-current))best=i;return best;}

 @Override protected void onStart(){super.onStart();if(toolbar.getTag()==null){polishToolbar();toolbar.setTag(Boolean.TRUE);}if(player==null)open();if(!wpCode.isEmpty()&&(wp==null||!wp.isOpen()))connectWatchParty();}
 void polishToolbar(){for(int i=toolbar.getChildCount()-1;i>1;i--){View divider=new View(this);divider.setBackgroundColor(0x66849a8b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(1),dp(28));p.setMargins(dp(3),0,dp(3),0);toolbar.addView(divider,i,p);}}
 void open(){Map<String,String> headers=new HashMap<>();headers.put("Referer",Config.REFERER);headers.put("User-Agent","Mozilla/5.0 (Linux; Android) Revayato/4.8 Media3");DefaultHttpDataSource.Factory http=new DefaultHttpDataSource.Factory().setUserAgent(headers.get("User-Agent")).setDefaultRequestProperties(headers).setConnectTimeoutMs(10000).setReadTimeoutMs(20000).setAllowCrossProtocolRedirects(true);DefaultDataSource.Factory data=new DefaultDataSource.Factory(this,http);DefaultLoadControl loadControl=new DefaultLoadControl.Builder().setAllocator(new DefaultAllocator(true,C.DEFAULT_BUFFER_SEGMENT_SIZE)).setBufferDurationsMs(8000,60000,1500,2500).setPrioritizeTimeOverSizeThresholds(true).build();DefaultRenderersFactory renderers=new DefaultRenderersFactory(this).setEnableDecoderFallback(true);player=new ExoPlayer.Builder(this,renderers).setLoadControl(loadControl).setMediaSourceFactory(new DefaultMediaSourceFactory(data)).build();player.setAudioAttributes(AudioAttributes.DEFAULT,true);player.setHandleAudioBecomingNoisy(true);playerView.setPlayer(player);player.setTrackSelectionParameters(player.getTrackSelectionParameters().buildUpon().setPreferredTextLanguage("fa").setSelectUndeterminedTextLanguage(true).build());player.addListener(new Player.Listener(){@Override public void onPlayerError(PlaybackException e){cancelStartupTimeout();int code=e.errorCode;boolean badHttp=code==PlaybackException.ERROR_CODE_IO_BAD_HTTP_STATUS;boolean network=code==PlaybackException.ERROR_CODE_IO_NETWORK_CONNECTION_FAILED||code==PlaybackException.ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT||code==PlaybackException.ERROR_CODE_IO_UNSPECIFIED;if(network&&blips<1){retrySameSource();return;}if(badHttp&&blips<1&&sourceIndex+1<sources.size()){blips=1;}if(!tryNextSource())showTerminalError(e);}@Override public void onPlaybackStateChanged(int state){if(state==Player.STATE_READY){sourceReady=true;blips=0;cancelStartupTimeout();sourceBadge.setText(sourceLabel());sourceBadge.animate().alpha(1f).setDuration(DUR_BASE).start();}if(state==Player.STATE_ENDED)getPreferences(0).edit().remove(key).apply();}
        @Override public void onIsPlayingChanged(boolean isPlaying){if(wpHost&&!wpApplying)emitPartyPlayback();}});prepareCurrent(Math.min(maxStart(),Math.max(0,position)));}
  void connectWatchParty(){try{wp=new WatchPartySocket(this,wpCode,new WatchPartySocket.Listener(){
   @Override public void onOpen(){if(wpHost)wp.startHostTimers();}
   @Override public void onPlaybackState(boolean playing,long positionSeconds,long durationSeconds){reconcileParty(playing,positionSeconds);}
   @Override public void onSyncResponse(boolean playing,long positionSeconds){reconcileParty(playing,positionSeconds);}
   @Override public void onError(String code,String message){if("token_expired".equals(code)||"unauthorized".equals(code)||"4401".equals(code)||"4403".equals(code)){Session.renew(PlayerActivity.this);}else if(!code.isEmpty())runOnUiThread(()->showFeedback("اتاق: "+message));}
   @Override public void onReconnecting(){runOnUiThread(()->showFeedback("اتصال مجدد به اتاق…"));reconcilingParty=true;}
   @Override public void onClosed(){if(reconcilingParty){reconcilingParty=false;return;}runOnUiThread(()->showFeedback("ارتباط با اتاق قطع شد"));}
  });wp.connect();}catch(Exception ignored){}}

  /** Guest: pull local player toward the host's authoritative state. */
  void reconcileParty(boolean playing,long positionSeconds){if(player==null||wpHost)return;long target=positionSeconds*1000;long here=player.getCurrentPosition();if(Math.abs(here-target)>2000){wpApplying=true;player.seekTo(target);wpApplying=false;}boolean shouldPlay=playing;if(player.isPlaying()!=shouldPlay){if(shouldPlay)player.play();else player.pause();}}

  void emitPartyPlayback(){if(wp==null||wpHost==false||player==null)return;long pos=Math.max(0,player.getCurrentPosition()/1000);if(player.isPlaying())wp.sendPlay(pos);else wp.sendPause(pos);}

  long maxStart(){if(player==null||player.getDuration()<=0)return Long.MAX_VALUE;return Math.max(0,player.getDuration()-800);}void prepareCurrent(long start){if(player==null)return;sourceReady=false;startupAnchor=start>0?start:0;cancelStartupTimeout();player.stop();player.clearMediaItems();player.setMediaItem(media(),start);player.prepare();player.setPlayWhenReady(playWhenReady);sourceBadge.setText("در حال اتصال · "+sourceLabel());handler.postDelayed(startupTimeout,45000);}
  void retrySameSource(){blips=1;cancelStartupTimeout();showFeedback("اتصال برقرار نشد؛ تلاش دوباره…");handler.postDelayed(()->{if(player==null)return;long p=player.getCurrentPosition();prepareCurrent(Math.min(maxStart(),Math.max(0,p>0?p:position)));},1400);}
  final Runnable startupTimeout=this::onStartupTimeout;void onStartupTimeout(){if(player==null||sourceReady||player.getPlaybackState()==Player.STATE_READY)return;long progress=player.getCurrentPosition();if(progress>startupAnchor+1500){startupAnchor=progress;handler.postDelayed(startupTimeout,45000);return;}if(blips<1){retrySameSource();return;}if(!tryNextSource())showTerminalError(null);}void cancelStartupTimeout(){handler.removeCallbacks(startupTimeout);}
 void showTerminalError(PlaybackException error){String detail=error==null?"منبع‌ها در زمان مناسب پاسخ ندادند.":playbackErrorMessage(error);new AlertDialog.Builder(this).setTitle("پخش انجام نشد").setMessage(detail+"\nهمه منابع این عنوان بررسی شدند. می‌توانید دوباره امتحان کنید یا همین منبع را با یک پلیر دیگر باز کنید.").setNegativeButton("بازگشت",(d,w)->finish()).setNeutralButton("پلیر دیگر",(d,w)->openExternalPlayer()).setPositiveButton("تلاش دوباره",(d,w)->retryCurrent()).show();}
 String playbackErrorMessage(PlaybackException error){String code=error.getErrorCodeName();if(error.errorCode==PlaybackException.ERROR_CODE_IO_NETWORK_CONNECTION_FAILED||error.errorCode==PlaybackException.ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT)return "اتصال به سرور ویدئو برقرار نشد.";if(error.errorCode==PlaybackException.ERROR_CODE_IO_BAD_HTTP_STATUS)return "سرور ویدئو درخواست پخش را نپذیرفت.";if(error.errorCode==PlaybackException.ERROR_CODE_DECODING_FORMAT_UNSUPPORTED||error.errorCode==PlaybackException.ERROR_CODE_DECODER_INIT_FAILED)return "این کدک روی دستگاه پشتیبانی نمی‌شود؛ منبع‌های سازگار دیگر هم بررسی شدند.";return "خطای پخش: "+code;}
 void openExternalPlayer(){try{Intent intent=new Intent(Intent.ACTION_VIEW,Uri.parse(url));String type=sourceMime(url);intent.setDataAndType(Uri.parse(url),type.isEmpty()?"video/*":type);intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(intent,"پخش با برنامه دیگر"));}catch(Exception e){Toast.makeText(this,"پلیر دیگری روی دستگاه پیدا نشد",Toast.LENGTH_LONG).show();}}
 void readSources(){LinkedHashSet<String> unique=new LinkedHashSet<>();if(!url.isEmpty())unique.add(url);try{JSONArray list=new JSONArray(safe(getIntent().getStringExtra("sources")));for(int i=0;i<list.length();i++){String value=list.optString(i).trim();if(value.startsWith("http://")||value.startsWith("https://"))unique.add(value);}}catch(Exception ignored){}sources.addAll(unique);sourceIndex=Math.max(0,sources.indexOf(url));}
  boolean tryNextSource(){if(player==null||sourceIndex+1>=sources.size())return false;cancelStartupTimeout();position=sourceReady?Math.max(position,player.getCurrentPosition()):position;playWhenReady=true;blips=0;url=sources.get(++sourceIndex);sourceBadge.setText(sourceLabel());showFeedback("منبع قبلی پاسخ نداد؛ منبع جایگزین فعال شد");handler.postDelayed(()->prepareCurrent(Math.min(maxStart(),Math.max(0,position))),300);return true;}void retryCurrent(){if(player==null)return;sourceIndex=0;blips=0;url=sources.isEmpty()?url:sources.get(0);showFeedback("بررسی دوباره همه منابع…");prepareCurrent(Math.min(maxStart(),Math.max(0,position)));}String sourceLabel(){String quality="";String x=safe(url).toLowerCase(Locale.ROOT);for(String q:new String[]{"2160","1080","720","480","360"})if(x.contains(q)){quality=q+"p · ";break;}return quality+"منبع "+Math.min(sourceIndex+1,Math.max(1,sources.size()))+" از "+Math.max(1,sources.size());}
 MediaItem media(){MediaItem.Builder m=new MediaItem.Builder().setUri(url).setMediaMetadata(new MediaMetadata.Builder().setTitle(getIntent().getStringExtra("title")).build());String sourceMime=sourceMime(url);if(!sourceMime.isEmpty())m.setMimeType(sourceMime);ArrayList<MediaItem.SubtitleConfiguration> subs=new ArrayList<>();try{JSONArray a=new JSONArray(tracks.isEmpty()?"[]":tracks);for(int i=0;i<a.length();i++){JSONObject t=a.getJSONObject(i);String src=safe(t.optString("src",t.optString("source_url",t.optString("url"))));String lower=src.toLowerCase(Locale.ROOT);if(!(lower.contains(".vtt")||lower.contains(".srt")||lower.contains(".ass")||lower.contains(".ssa")||lower.contains(".ttml")||lower.contains(".xml")))continue;subs.add(sub(Uri.parse(src),mime(src),t.optString("language",t.optString("srclang","fa")),t.optString("label","فارسی"),i==0));}}catch(Exception ignored){}if(imported!=null)subs.add(sub(imported,mime(displayName(imported)),"fa","زیرنویس انتخابی",true));return m.setSubtitleConfigurations(subs).build();}
  String sourceMime(String value){String s=safe(value).toLowerCase(Locale.ROOT);if(s.contains(".m3u8"))return MimeTypes.APPLICATION_M3U8;if(s.contains(".mpd"))return MimeTypes.APPLICATION_MPD;if(s.contains(".webm"))return MimeTypes.VIDEO_WEBM;if(s.contains(".mkv")||s.contains(".mka"))return MimeTypes.VIDEO_MATROSKA;if(s.contains(".mp4")||s.contains(".m4v")||s.contains(".mov"))return MimeTypes.VIDEO_MP4;return "";}
 MediaItem.SubtitleConfiguration sub(Uri uri,String mime,String language,String label,boolean selected){return new MediaItem.SubtitleConfiguration.Builder(uri).setMimeType(mime).setLanguage(language).setLabel(label).setSelectionFlags(selected?C.SELECTION_FLAG_DEFAULT:0).build();}
 void chooseSubtitle(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/x-subrip","text/vtt","text/plain","text/x-ssa","application/ttml+xml"});startActivityForResult(i,PICK_SUBTITLE);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=PICK_SUBTITLE||result!=RESULT_OK||data==null||data.getData()==null)return;imported=data.getData();try{getContentResolver().takePersistableUriPermission(imported,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}if(player!=null){position=player.getCurrentPosition();playWhenReady=player.getPlayWhenReady();player.setMediaItem(media(),position);player.prepare();player.setPlayWhenReady(playWhenReady);}showFeedback("زیرنویس اضافه شد");}
 String displayName(Uri uri){try(Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception ignored){}return uri.toString();}String mime(String name){String s=safe(name).toLowerCase(Locale.ROOT);if(s.contains(".srt"))return MimeTypes.APPLICATION_SUBRIP;if(s.contains(".ass")||s.contains(".ssa"))return MimeTypes.TEXT_SSA;if(s.contains(".ttml")||s.contains(".xml"))return MimeTypes.APPLICATION_TTML;return MimeTypes.TEXT_VTT;}

 boolean hasTracks(){try{return new JSONArray(tracks.isEmpty()?"[]":tracks).length()>0;}catch(Exception e){return false;}}void reportMissing(){String slug=safe(getIntent().getStringExtra("slug")),type=safe(getIntent().getStringExtra("content_type"));if(slug.isEmpty()||type.isEmpty())return;network.execute(()->{try{JSONObject b=new JSONObject().put("content_type",type).put("slug",slug).put("episode_id",getIntent().getIntExtra("episode_id",0)).put("version","").put("source_url",url).put("sync",true);Session.Reply reply=Session.call(this,"POST",Session.API+"catalog/playback-subtitle-ensure/",b);if(reply.ok())runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())Toast.makeText(this,"زیرنویس فارسی به‌صورت خودکار در حال بررسی است",Toast.LENGTH_LONG).show();});}catch(Exception ignored){}});}
   void save(){if(player==null)return;position=player.getCurrentPosition();playWhenReady=player.getPlayWhenReady();if(position>5000){getPreferences(0).edit().putLong(key,position).apply();persistResumeMeta(position);}else if(position<=5000){getPreferences(0).edit().remove(key).apply();}}
  /** Persist a resume card for the Continue-Watching rail (title/poster/slug/type). */
  void persistResumeMeta(long positionMs){try{String slug=safe(getIntent().getStringExtra("slug"));if(slug.isEmpty())return;String type=safe(getIntent().getStringExtra("content_type"));String title=safe(getIntent().getStringExtra("title"));org.json.JSONObject m=new org.json.JSONObject();m.put("slug",slug).put("type",type).put("title",title).put("position",positionMs).put("poster",safe(getIntent().getStringExtra("poster")));getPreferences(0).edit().putString("resume_meta:"+slug+"|"+type, m.toString()).apply();}catch(Exception ignored){}}@Override protected void onStop(){cancelStartupTimeout();save();if(wp!=null)wp.leaveAndClose();boolean keep=Build.VERSION.SDK_INT>=26&&isInPictureInPictureMode();if(player!=null&&!keep){player.release();player=null;}super.onStop();}@Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);if(wp!=null)wp.close();network.shutdownNow();super.onDestroy();}@Override protected void onSaveInstanceState(Bundle b){save();b.putLong("position",position);if(imported!=null)b.putString("imported",imported.toString());super.onSaveInstanceState(b);}
 void enterPip(){if(Build.VERSION.SDK_INT>=26&&player!=null)try{enterPictureInPictureMode(new PictureInPictureParams.Builder().setAspectRatio(new Rational(16,9)).build());}catch(Exception ignored){}}@Override public void onUserLeaveHint(){super.onUserLeaveHint();if(player!=null&&player.isPlaying())enterPip();}@Override public void onPictureInPictureModeChanged(boolean pip,Configuration c){super.onPictureInPictureModeChanged(pip,c);playerView.setUseController(!pip&&!locked);toolbar.setVisibility(pip?View.GONE:View.VISIBLE);if(!pip&&player==null&&c!=null){open();}} 
 GradientDrawable pill(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}void immersive(){getWindow().getDecorView().setSystemUiVisibility(5894);}int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}static String safe(String s){return s==null?"":s;}
}
