# Generated by Django 5.2.16 on 2026-07-16 14:07

import apps.watchparty.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_movie_content_format_movie_content_warnings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(db_index=True, default=apps.watchparty.models.generate_invite_code, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], db_index=True, default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.watchparty.models.default_room_expiry)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_rooms', to='catalog.episode')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_watch_rooms', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_rooms', to='catalog.movie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='watchparty.watchroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='watchparty.watchroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchRoomPlaybackState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_playing', models.BooleanField(default=False)),
                ('position_seconds', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_seconds', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('playback_rate', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(4)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_state', to='watchparty.watchroom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_room_playback_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='watchroom',
            index=models.Index(fields=['status', 'expires_at'], name='watchparty__status_99bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='watchroom',
            index=models.Index(fields=['host_user', '-created_at'], name='watchparty__host_us_3de87b_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('episode__isnull', True), ('movie__isnull', False)), models.Q(('episode__isnull', False), ('movie__isnull', True)), _connector='OR'), name='watchroom_exactly_one_content'),
        ),
        migrations.AddIndex(
            model_name='watchroommember',
            index=models.Index(fields=['room', 'is_online'], name='watchparty__room_id_7b22bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchroommember',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='watchroom_unique_member'),
        ),
        migrations.AddConstraint(
            model_name='watchroommember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'host')), fields=('room',), name='watchroom_single_host_member'),
        ),
        migrations.AddIndex(
            model_name='watchroommessage',
            index=models.Index(fields=['room', 'is_deleted', '-created_at'], name='watchparty__room_id_c46184_idx'),
        ),
    ]
