"""Canonical Persian country names used by public catalog responses and imports."""

COUNTRY_NAME_BY_CODE = {
    'AE': 'امارات متحده عربی',
    'AL': 'آلبانی',
    'AR': 'آرژانتین',
    'AT': 'اتریش',
    'AU': 'استرالیا',
    'AZ': 'آذربایجان',
    'BE': 'بلژیک',
    'BG': 'بلغارستان',
    'BH': 'بحرین',
    'BR': 'برزیل',
    'CA': 'کانادا',
    'CH': 'سوئیس',
    'CL': 'شیلی',
    'CN': 'چین',
    'CO': 'کلمبیا',
    'CU': 'کوبا',
    'CY': 'قبرس',
    'CZ': 'جمهوری چک',
    'DE': 'آلمان',
    'DK': 'دانمارک',
    'EG': 'مصر',
    'ES': 'اسپانیا',
    'FI': 'فنلاند',
    'FR': 'فرانسه',
    'GB': 'بریتانیا',
    'GE': 'گرجستان',
    'GR': 'یونان',
    'HK': 'هنگ‌کنگ',
    'HR': 'کرواسی',
    'HU': 'مجارستان',
    'ID': 'اندونزی',
    'IE': 'ایرلند',
    'IL': 'اسرائیل',
    'IN': 'هند',
    'IQ': 'عراق',
    'IR': 'ایران',
    'IS': 'ایسلند',
    'IT': 'ایتالیا',
    'JO': 'اردن',
    'JP': 'ژاپن',
    'KR': 'کره جنوبی',
    'KW': 'کویت',
    'LB': 'لبنان',
    'LK': 'سری‌لانکا',
    'LT': 'لیتوانی',
    'LU': 'لوکزامبورگ',
    'LV': 'لتونی',
    'MA': 'مراکش',
    'MK': 'مقدونیه شمالی',
    'MX': 'مکزیک',
    'MY': 'مالزی',
    'NG': 'نیجریه',
    'NL': 'هلند',
    'NO': 'نروژ',
    'NZ': 'نیوزیلند',
    'PE': 'پرو',
    'PH': 'فیلیپین',
    'PK': 'پاکستان',
    'PL': 'لهستان',
    'PS': 'فلسطین',
    'PT': 'پرتغال',
    'QA': 'قطر',
    'RO': 'رومانی',
    'RS': 'صربستان',
    'RU': 'روسیه',
    'SA': 'عربستان سعودی',
    'SE': 'سوئد',
    'SG': 'سنگاپور',
    'SK': 'اسلواکی',
    'SU': 'اتحاد جماهیر شوروی',
    'TH': 'تایلند',
    'TN': 'تونس',
    'TR': 'ترکیه',
    'TW': 'تایوان',
    'UA': 'اوکراین',
    'US': 'آمریکا',
    'VN': 'ویتنام',
    'XK': 'کوزوو',
    'ZA': 'آفریقای جنوبی',
}

COUNTRY_CODE_BY_PERSIAN_NAME = {
    name: code for code, name in COUNTRY_NAME_BY_CODE.items()
}

COUNTRY_CODE_BY_ENGLISH_NAME = {
    'albania': 'AL',
    'argentina': 'AR',
    'australia': 'AU',
    'austria': 'AT',
    'azerbaijan': 'AZ',
    'bahrain': 'BH',
    'belgium': 'BE',
    'brazil': 'BR',
    'bulgaria': 'BG',
    'canada': 'CA',
    'chile': 'CL',
    'china': 'CN',
    'colombia': 'CO',
    'croatia': 'HR',
    'cuba': 'CU',
    'cyprus': 'CY',
    'czech republic': 'CZ',
    'czechia': 'CZ',
    'denmark': 'DK',
    'egypt': 'EG',
    'finland': 'FI',
    'france': 'FR',
    'georgia': 'GE',
    'germany': 'DE',
    'great britain': 'GB',
    'greece': 'GR',
    'hong kong': 'HK',
    'hungary': 'HU',
    'iceland': 'IS',
    'india': 'IN',
    'indonesia': 'ID',
    'iran': 'IR',
    'iraq': 'IQ',
    'ireland': 'IE',
    'israel': 'IL',
    'italy': 'IT',
    'japan': 'JP',
    'jordan': 'JO',
    'kosovo': 'XK',
    'kuwait': 'KW',
    'latvia': 'LV',
    'lebanon': 'LB',
    'lithuania': 'LT',
    'luxembourg': 'LU',
    'macedonia': 'MK',
    'malaysia': 'MY',
    'mexico': 'MX',
    'morocco': 'MA',
    'netherlands': 'NL',
    'new zealand': 'NZ',
    'nigeria': 'NG',
    'north macedonia': 'MK',
    'norway': 'NO',
    'pakistan': 'PK',
    'palestine': 'PS',
    'peru': 'PE',
    'philippines': 'PH',
    'poland': 'PL',
    'portugal': 'PT',
    'qatar': 'QA',
    'romania': 'RO',
    'russia': 'RU',
    'saudi arabia': 'SA',
    'serbia': 'RS',
    'singapore': 'SG',
    'slovakia': 'SK',
    'south africa': 'ZA',
    'south korea': 'KR',
    'soviet union': 'SU',
    'spain': 'ES',
    'sri lanka': 'LK',
    'sweden': 'SE',
    'switzerland': 'CH',
    'taiwan': 'TW',
    'thailand': 'TH',
    'tunisia': 'TN',
    'turkey': 'TR',
    'ukraine': 'UA',
    'united arab emirates': 'AE',
    'united kingdom': 'GB',
    'united states': 'US',
    'united states of america': 'US',
    'usa': 'US',
    'vietnam': 'VN',
}


def persian_country_name(code, fallback=''):
    normalized_code = (code or '').strip().upper()
    return COUNTRY_NAME_BY_CODE.get(normalized_code) or (fallback or normalized_code).strip()


def country_code_for_name(name):
    """Resolve Persian name, English name, or ISO code to an uppercase ISO code."""
    value = (name or '').strip()
    if not value:
        return ''
    if len(value) == 2 and value.isalpha():
        return value.upper()
    persian = COUNTRY_CODE_BY_PERSIAN_NAME.get(value)
    if persian:
        return persian
    english = COUNTRY_CODE_BY_ENGLISH_NAME.get(value.lower())
    if english:
        return english
    return value
