# Generated by Django 5.2.16 on 2026-07-14 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_data', models.JSONField(default=dict)),
                ('is_ready', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('reason_details', models.JSONField(blank=True, default=dict)),
                ('is_consumed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', '-score'], name='recommendat_user_id_741c53_idx'), models.Index(fields=['session_key', '-score'], name='recommendat_session_780187_idx')],
                'unique_together': {('session_key', 'content_type', 'object_id'), ('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('clicked_content_type', models.CharField(blank=True, max_length=50)),
                ('clicked_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query'], name='recommendat_query_070f0d_idx'), models.Index(fields=['user', '-created_at'], name='recommendat_user_id_53ef8e_idx')],
            },
        ),
    ]
