# Generated by Django 5.2.16 on 2026-07-14 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('episode', 'Episode'), ('actor', 'Actor'), ('director', 'Director'), ('genre', 'Genre'), ('search', 'Search')], max_length=50)),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('view_movie', 'View Movie'), ('view_series', 'View Series'), ('view_episode', 'View Episode'), ('play', 'Play'), ('pause', 'Pause'), ('watch_progress', 'Watch Progress'), ('complete_watch', 'Complete Watch'), ('like', 'Like'), ('dislike', 'Dislike'), ('rate', 'Rate'), ('add_to_watchlist', 'Add to Watchlist'), ('remove_from_watchlist', 'Remove from Watchlist'), ('search', 'Search'), ('click_search_result', 'Click Search Result'), ('filter_genre', 'Filter Genre'), ('filter_year', 'Filter Year'), ('filter_country', 'Filter Country'), ('open_actor_page', 'Open Actor Page'), ('open_director_page', 'Open Director Page'), ('share', 'Share'), ('comment', 'Comment'), ('download_click', 'Download Click'), ('trailer_watch', 'Trailer Watch')], db_index=True, max_length=50)),
                ('value', models.FloatField(default=1.0)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='engagement__user_id_30ca5c_idx'), models.Index(fields=['content_type', 'object_id'], name='engagement__content_a8bad7_idx'), models.Index(fields=['session_key', 'created_at'], name='engagement__session_f93e72_idx')],
            },
        ),
    ]
