# Generated by Django 5.2.16 on 2026-07-14 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(db_index=True, verbose_name='Season Number')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Release Year')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/seasons/posters/', verbose_name='Poster')),
                ('episode_count', models.PositiveIntegerField(default=0, verbose_name='Episode Count')),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='Air Date')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['series', 'season_number'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='Slug')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog/actors/', verbose_name='Photo')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Birth Date')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='Birth Place')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('popularity', models.FloatField(db_index=True, default=0.0, verbose_name='Popularity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['-popularity', 'name'], name='catalog_act_popular_ae93a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog/directors/', verbose_name='Photo')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('birth_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Birth Date')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='Birth Place')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('popularity', models.FloatField(db_index=True, default=0.0, verbose_name='Popularity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['-popularity', 'name'], name='catalog_dir_popular_1a3ea1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='Original Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('release_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Release Year')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (Minutes)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/movies/posters/', verbose_name='Poster')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='catalog/movies/backdrops/', verbose_name='Backdrop')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Trailer URL')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='IMDb Rating')),
                ('site_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Site Rating')),
                ('age_rating', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Age Rating')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Language')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='View Count')),
                ('like_count', models.PositiveBigIntegerField(default=0, verbose_name='Like Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='movies', to='catalog.country', verbose_name='Countries')),
                ('directors', models.ManyToManyField(blank=True, related_name='movies', to='catalog.director', verbose_name='Directors')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='catalog.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Role')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Lead Role')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_roles', to='catalog.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_actors', to='catalog.movie')),
            ],
            options={
                'verbose_name': 'Movie Actor',
                'verbose_name_plural': 'Movie Actors',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', through='catalog.MovieActor', to='catalog.actor', verbose_name='Actors'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(db_index=True, verbose_name='Episode Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (Minutes)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/episodes/posters/', verbose_name='Poster')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Trailer URL')),
                ('air_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Air Date')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.season', verbose_name='Season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['season', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='Original Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Start Year')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Year')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/series/posters/', verbose_name='Poster')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='catalog/series/backdrops/', verbose_name='Backdrop')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Trailer URL')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='IMDb Rating')),
                ('site_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Site Rating')),
                ('age_rating', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Age Rating')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Language')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('ended', 'Ended'), ('upcoming', 'Upcoming'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], db_index=True, default='ongoing', max_length=20, verbose_name='Status')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='View Count')),
                ('like_count', models.PositiveBigIntegerField(default=0, verbose_name='Like Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='series', to='catalog.country', verbose_name='Countries')),
                ('directors', models.ManyToManyField(blank=True, related_name='series', to='catalog.director', verbose_name='Directors')),
                ('genres', models.ManyToManyField(blank=True, related_name='series', to='catalog.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.series', verbose_name='Series'),
        ),
        migrations.CreateModel(
            name='SeriesActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Role')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Lead Role')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_roles', to='catalog.actor')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_actors', to='catalog.series')),
            ],
            options={
                'verbose_name': 'Series Actor',
                'verbose_name_plural': 'Series Actors',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='series', through='catalog.SeriesActor', to='catalog.actor', verbose_name='Actors'),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='series', to='catalog.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.tag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='movieactor',
            constraint=models.UniqueConstraint(fields=('movie', 'actor'), name='uq_movie_actor'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'episode_number'], name='catalog_epi_season__ffe9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'is_published'], name='catalog_epi_season__f4587b_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['air_date', 'is_published'], name='catalog_epi_air_dat_c8f884_idx'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_number'), name='uq_season_episode'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['series', 'season_number'], name='catalog_sea_series__25cb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['series', 'is_published'], name='catalog_sea_series__3086e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('series', 'season_number'), name='uq_series_season'),
        ),
        migrations.AddConstraint(
            model_name='seriesactor',
            constraint=models.UniqueConstraint(fields=('series', 'actor'), name='uq_series_actor'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['-start_year', 'is_published'], name='catalog_ser_start_y_e7ea7f_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_published', '-view_count'], name='catalog_ser_is_publ_0d60ed_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['slug', 'is_published'], name='catalog_ser_slug_b53fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['status', 'is_published'], name='catalog_ser_status_86097b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_year', 'is_published'], name='catalog_mov_release_55a6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_published', '-view_count'], name='catalog_mov_is_publ_df37f0_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug', 'is_published'], name='catalog_mov_slug_616778_idx'),
        ),
    ]
