# Generated by Django 5.2.16 on 2026-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMDb ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='TMDb ID'),
        ),
    ]
