# Generated by Django 5.2.16 on 2026-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_movie_imdb_id_movie_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_format',
            field=models.CharField(choices=[('live_action', 'Live Action'), ('animation', 'Animation'), ('short', 'Short')], db_index=True, default='live_action', max_length=20, verbose_name='Content Format'),
        ),
        migrations.AddField(
            model_name='movie',
            name='content_warnings',
            field=models.JSONField(blank=True, default=list, verbose_name='Content Warnings'),
        ),
        migrations.AddField(
            model_name='movie',
            name='has_subtitle',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Has Subtitle'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_dubbed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Dubbed'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_uncensored',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Uncensored'),
        ),
        migrations.AddField(
            model_name='series',
            name='content_format',
            field=models.CharField(choices=[('live_action', 'Live Action'), ('animation', 'Animation'), ('short', 'Short')], db_index=True, default='live_action', max_length=20, verbose_name='Content Format'),
        ),
        migrations.AddField(
            model_name='series',
            name='content_warnings',
            field=models.JSONField(blank=True, default=list, verbose_name='Content Warnings'),
        ),
        migrations.AddField(
            model_name='series',
            name='has_subtitle',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Has Subtitle'),
        ),
        migrations.AddField(
            model_name='series',
            name='is_dubbed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Dubbed'),
        ),
        migrations.AddField(
            model_name='series',
            name='is_uncensored',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Uncensored'),
        ),
    ]
