# Generated by Django 5.2.16 on 2026-07-18 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_publication_state(apps, schema_editor):
    Movie = apps.get_model('catalog', 'Movie')
    Movie.objects.filter(is_published=True).update(publication_status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalog_ingestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSyncAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Import'), ('sync', 'Sync'), ('manual_create', 'Manual create'), ('manual_update', 'Manual update'), ('archive', 'Archive')], db_index=True, max_length=30)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('overwrite', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('skipped_fields', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='profile_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='TMDb profile path'),
        ),
        migrations.AddField(
            model_name='actor',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='TMDb ID'),
        ),
        migrations.AddField(
            model_name='director',
            name='profile_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='TMDb profile path'),
        ),
        migrations.AddField(
            model_name='director',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='TMDb ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_external_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='External backdrop URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='catalog_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('documentary', 'Documentary'), ('short', 'Short')], db_index=True, default='movie', max_length=20, verbose_name='Catalog type'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew_metadata',
            field=models.JSONField(blank=True, default=list, verbose_name='Crew metadata'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Recommended'),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_tmdb_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last TMDb sync'),
        ),
        migrations.AddField(
            model_name='movie',
            name='manual_override_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Manually edited fields'),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='TMDb popularity'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_external_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='External poster URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.JSONField(blank=True, default=list, verbose_name='Production companies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Publication status'),
        ),
        migrations.RunPython(preserve_existing_publication_state, migrations.RunPython.noop),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(blank=True, max_length=80, verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='SEO keywords'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='Spoken languages'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_external_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='External trailer URL'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='TMDb vote count'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.JSONField(blank=True, default=list, verbose_name='Writers'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['publication_status', '-updated_at'], name='catalog_mov_publica_954b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['catalog_type', 'publication_status'], name='catalog_mov_catalog_f34a2b_idx'),
        ),
        migrations.AddField(
            model_name='moviesyncaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_sync_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moviesyncaudit',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_audits', to='catalog.movie'),
        ),
        migrations.AddIndex(
            model_name='moviesyncaudit',
            index=models.Index(fields=['movie', '-created_at'], name='catalog_mov_movie_i_7f9d8e_idx'),
        ),
    ]
