"""Reconcile production catalog sync / importer schema with current models.

Earlier environments applied differently-named migrations
(``0009_catalogsyncrun_active_lock_and_more``, ``0010_catalog_importer_settings``).
This migration brings the live schema in line with ``models.py`` safely.
"""

from django.conf import settings
from django.db import migrations


def _column_names(schema_editor, table):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table)
    return {column.name for column in description}


def _has_table(schema_editor, table):
    return table in schema_editor.connection.introspection.table_names()


def _user_table():
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    return f'{app_label}_{model_name.lower()}'


def reconcile_schema(apps, schema_editor):
    connection = schema_editor.connection
    quote = connection.ops.quote_name
    user_table = _user_table()

    if _has_table(schema_editor, 'catalog_catalogsyncrun'):
        columns = _column_names(schema_editor, 'catalog_catalogsyncrun')
        with connection.cursor() as cursor:
            if 'phase' not in columns:
                cursor.execute(
                    f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                    f"ADD COLUMN {quote('phase')} varchar(40) DEFAULT 'queued' NOT NULL"
                )
            if 'parameters' not in columns:
                cursor.execute(
                    f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                    f"ADD COLUMN {quote('parameters')} jsonb DEFAULT '{{}}'::jsonb NOT NULL"
                )
            if 'updated_at' not in columns:
                cursor.execute(
                    f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                    f'ADD COLUMN {quote("updated_at")} timestamptz DEFAULT NOW() NOT NULL'
                )
            if 'cancel_requested_at' not in columns:
                cursor.execute(
                    f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                    f'ADD COLUMN {quote("cancel_requested_at")} timestamptz NULL'
                )
            if 'task_id' not in columns:
                cursor.execute(
                    f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                    f"ADD COLUMN {quote('task_id')} varchar(255) DEFAULT '' NOT NULL"
                )
                if 'celery_task_id' in columns:
                    cursor.execute(
                        f'UPDATE {quote("catalog_catalogsyncrun")} '
                        f'SET {quote("task_id")} = COALESCE({quote("celery_task_id")}, \'\')'
                    )
            if 'requested_by_id' not in columns:
                cursor.execute(
                    f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                    f'ADD COLUMN {quote("requested_by_id")} bigint NULL'
                )
                if 'created_by_id' in columns:
                    cursor.execute(
                        f'UPDATE {quote("catalog_catalogsyncrun")} '
                        f'SET {quote("requested_by_id")} = {quote("created_by_id")}'
                    )
                if _has_table(schema_editor, user_table):
                    cursor.execute(
                        f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                        f'ADD CONSTRAINT {quote("catalog_catalogsyncrun_requested_by_id_fk")} '
                        f'FOREIGN KEY ({quote("requested_by_id")}) '
                        f'REFERENCES {quote(user_table)}(id) DEFERRABLE INITIALLY DEFERRED'
                    )
            cursor.execute(
                f'ALTER TABLE {quote("catalog_catalogsyncrun")} '
                f'ALTER COLUMN {quote("mode")} TYPE varchar(24)'
            )
            cursor.execute('DROP INDEX IF EXISTS uq_active_catalog_sync_provider')
            cursor.execute(
                'CREATE UNIQUE INDEX IF NOT EXISTS catalog_one_active_sync_per_provider '
                'ON catalog_catalogsyncrun (provider) '
                "WHERE status IN ('queued', 'running', 'cancelling')"
            )

    if not _has_table(schema_editor, 'catalog_catalogsynccandidate'):
        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TABLE catalog_catalogsynccandidate (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tmdb_id integer NOT NULL CHECK (tmdb_id >= 0),
                    status varchar(20) NOT NULL,
                    popularity double precision NOT NULL,
                    attempts smallint NOT NULL CHECK (attempts >= 0),
                    error varchar(500) NOT NULL,
                    created_at timestamptz NOT NULL,
                    updated_at timestamptz NOT NULL,
                    run_id bigint NOT NULL
                        REFERENCES catalog_catalogsyncrun(id) DEFERRABLE INITIALLY DEFERRED
                )
                """
            )
            cursor.execute(
                'CREATE UNIQUE INDEX catalog_unique_sync_candidate '
                'ON catalog_catalogsynccandidate (run_id, tmdb_id)'
            )
            cursor.execute(
                'CREATE INDEX catalog_sync_work_idx '
                'ON catalog_catalogsynccandidate (run_id, status, id)'
            )

    for table in ('catalog_actor', 'catalog_director'):
        if _has_table(schema_editor, table) and 'photo_external_url' not in _column_names(schema_editor, table):
            with connection.cursor() as cursor:
                cursor.execute(
                    f'ALTER TABLE {quote(table)} '
                    f"ADD COLUMN {quote('photo_external_url')} varchar(500) DEFAULT '' NOT NULL"
                )

    with connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS catalog_catalogimportersettings CASCADE')
        cursor.execute(
            f"""
            CREATE TABLE catalog_catalogimportersettings (
                id smallint PRIMARY KEY,
                language varchar(10) NOT NULL,
                fallback_language varchar(10) NOT NULL,
                region varchar(2) NOT NULL,
                daily_lookback_days smallint NOT NULL CHECK (daily_lookback_days >= 0),
                daily_lookahead_days smallint NOT NULL CHECK (daily_lookahead_days >= 0),
                daily_max_pages smallint NOT NULL CHECK (daily_max_pages >= 0),
                trending_window varchar(8) NOT NULL,
                trending_max_pages smallint NOT NULL CHECK (trending_max_pages >= 0),
                import_people_images boolean NOT NULL,
                fetch_imdb_ratings boolean NOT NULL,
                feature_trending boolean NOT NULL,
                auto_publish boolean NOT NULL,
                automation_enabled boolean NOT NULL,
                automation_mode varchar(12) NOT NULL,
                automation_interval_hours smallint NOT NULL CHECK (automation_interval_hours >= 0),
                updated_at timestamptz NOT NULL,
                updated_by_id bigint NULL
                    REFERENCES {quote(user_table)}(id) DEFERRABLE INITIALLY DEFERRED
            )
            """
        )
        cursor.execute(
            """
            INSERT INTO catalog_catalogimportersettings (
                id, language, fallback_language, region,
                daily_lookback_days, daily_lookahead_days, daily_max_pages,
                trending_window, trending_max_pages,
                import_people_images, fetch_imdb_ratings, feature_trending,
                auto_publish, automation_enabled, automation_mode, automation_interval_hours,
                updated_at
            ) VALUES (
                1, 'fa-IR', 'en-US', 'IR',
                2, 7, 5,
                'day', 3,
                TRUE, TRUE, TRUE,
                FALSE, FALSE, 'daily', 24,
                NOW()
            )
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_importer_settings_and_people_photos'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(reconcile_schema, migrations.RunPython.noop),
            ],
            state_operations=[],
        ),
    ]
