# Generated by Django 5.2.16 on 2026-07-19 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_restore_persian_genre_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_mode', models.CharField(choices=[('env', 'Environment variables'), ('encrypted', 'Encrypted vault')], default='env', max_length=20, verbose_name='Secret mode')),
                ('env_prefix', models.CharField(default='AVASARAMI', max_length=40, verbose_name='Env prefix')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('configured', 'Configured'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('needs_interactive', 'Needs interactive verification')], db_index=True, default='unknown', max_length=32, verbose_name='Status')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider credential',
                'verbose_name_plural': 'Provider credentials',
            },
        ),
        migrations.CreateModel(
            name='ProviderImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_item_id', models.CharField(db_index=True, max_length=255)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('episode', 'Episode')], default='movie', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('selected_candidate', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('matched', 'Matched'), ('skipped', 'Skipped'), ('downloading', 'Downloading'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], db_index=True, default='discovered', max_length=20)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider import item',
                'verbose_name_plural': 'Provider import items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('movies', 'Movies'), ('series', 'Series'), ('both', 'Both')], default='movies', max_length=16, verbose_name='Content type')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('cancel_requested', 'Cancel requested'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32, verbose_name='Status')),
                ('mode', models.CharField(choices=[('discover_only', 'Discover only'), ('import_missing_files', 'Import missing files'), ('import_selected', 'Import selected'), ('sync_all', 'Sync all')], default='discover_only', max_length=32, verbose_name='Mode')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('matched_items', models.PositiveIntegerField(default=0)),
                ('imported_files', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('current_item_label', models.CharField(blank=True, max_length=255)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider import job',
                'verbose_name_plural': 'Provider import jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=16)),
                ('message', models.CharField(max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Provider import log',
                'verbose_name_plural': 'Provider import logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('provider_type', models.CharField(choices=[('api', 'API'), ('feed', 'Feed'), ('cookie_session', 'Cookie session'), ('session_login', 'Session login'), ('static_links', 'Static links'), ('custom', 'Custom')], default='custom', max_length=32, verbose_name='Provider type')),
                ('base_url', models.URLField(blank=True, max_length=500, verbose_name='Base URL')),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API key'), ('bearer_token', 'Bearer token'), ('username_password', 'Username / password'), ('cookie_session', 'Cookie session'), ('feed', 'Feed')], default='none', max_length=32, verbose_name='Auth type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=30, verbose_name='Rate limit / minute')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='Timeout (seconds)')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='Verify SSL')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Non-secret config')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider source',
                'verbose_name_plural': 'Provider sources',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='moviearchiveasset',
            new_name='catalog_mov_movie_i_e18641_idx',
            old_name='catalog_mov_movie_i_7c0f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='moviearchiveasset',
            new_name='catalog_mov_status_948e45_idx',
            old_name='catalog_mov_status_5e2b9c_idx',
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='archive_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_import_items', to='catalog.moviearchiveasset'),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='matched_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_import_items', to='catalog.episode'),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='matched_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_import_items', to='catalog.movie'),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='matched_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_import_items', to='catalog.series'),
        ),
        migrations.AddField(
            model_name='providerimportjob',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.providerimportjob'),
        ),
        migrations.AddField(
            model_name='providerimportlog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='catalog.providerimportjob'),
        ),
        migrations.AddField(
            model_name='providerimportjob',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='catalog.providersource'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='catalog.providersource'),
        ),
        migrations.AddIndex(
            model_name='providerimportitem',
            index=models.Index(fields=['job', 'status'], name='catalog_pro_job_id_5d5cef_idx'),
        ),
        migrations.AddIndex(
            model_name='providerimportitem',
            index=models.Index(fields=['job', 'provider_item_id'], name='catalog_pro_job_id_1738b0_idx'),
        ),
        migrations.AddIndex(
            model_name='providerimportjob',
            index=models.Index(fields=['provider', 'status'], name='catalog_pro_provide_86cd64_idx'),
        ),
        migrations.AddIndex(
            model_name='providerimportjob',
            index=models.Index(fields=['status', '-created_at'], name='catalog_pro_status_7e46d9_idx'),
        ),
    ]
