# Generated by Django 5.2.16 on 2026-07-19 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_provider_import_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providercredential',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='manually_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='match_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='providerimportitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerimportjob',
            name='sanitized_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='providerimportjob',
            name='target_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_import_jobs', to='catalog.movie'),
        ),
        migrations.AddField(
            model_name='providerimportjob',
            name='target_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_import_jobs', to='catalog.series'),
        ),
        migrations.AddField(
            model_name='providerimportjob',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('movie_created', 'Movie created'), ('movie_updated', 'Movie updated'), ('series_created', 'Series created'), ('series_updated', 'Series updated'), ('scheduled_retry', 'Scheduled retry')], db_index=True, default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='providerimportlog',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='providerimportitem',
            name='status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('matched', 'Matched'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('skipped', 'Skipped'), ('downloading', 'Downloading'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], db_index=True, default='discovered', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerimportjob',
            name='content_type',
            field=models.CharField(choices=[('movies', 'Movies'), ('series', 'Series'), ('both', 'Both'), ('movie', 'Movie')], default='movies', max_length=16, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='providerimportjob',
            name='mode',
            field=models.CharField(choices=[('discover_only', 'Discover only'), ('import_missing_files', 'Import missing files'), ('import_selected', 'Import selected'), ('import_missing', 'Import missing'), ('sync_all', 'Sync all')], default='discover_only', max_length=32, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='providerimportjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('searching', 'Searching'), ('awaiting_review', 'Awaiting review'), ('running', 'Running'), ('transferring', 'Transferring'), ('cancel_requested', 'Cancel requested'), ('completed', 'Completed'), ('partially_completed', 'Partially completed'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='providerimportjob',
            index=models.Index(fields=['target_movie', 'status'], name='catalog_pro_target__17acfa_idx'),
        ),
        migrations.AddIndex(
            model_name='providerimportjob',
            index=models.Index(fields=['target_series', 'status'], name='catalog_pro_target__94e41f_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerimportitem',
            constraint=models.UniqueConstraint(fields=('job', 'provider_item_id', 'content_type'), name='uniq_provider_item_per_job'),
        ),
        migrations.AddConstraint(
            model_name='providerimportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'validating', 'searching', 'awaiting_review', 'running', 'transferring', 'cancel_requested']), ('target_movie__isnull', False)), fields=('provider', 'target_movie', 'mode'), name='uniq_active_provider_movie_job'),
        ),
        migrations.AddConstraint(
            model_name='providerimportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'validating', 'searching', 'awaiting_review', 'running', 'transferring', 'cancel_requested']), ('target_series__isnull', False)), fields=('provider', 'target_series', 'mode'), name='uniq_active_provider_series_job'),
        ),
    ]
