# Generated by Django 5.2.16 on 2026-07-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_series_download_links'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_published', '-updated_at'], name='catalog_mov_is_publ_ae673c_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_published', '-updated_at'], name='catalog_ser_is_publ_9acbc6_idx'),
        ),
    ]
