# Generated by Django 5.2.17 on 2026-08-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_catalog_hot_path_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('original_title', models.CharField(blank=True, max_length=200, verbose_name='Original title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/collections/posters/', verbose_name='Poster')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='catalog/collections/backdrops/', verbose_name='Backdrop')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CollectionMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_movies', to='catalog.collection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_movies', to='catalog.movie')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('collection', 'movie')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='collections', through='catalog.CollectionMovie', through_fields=('collection', 'movie'), to='catalog.movie'),
        ),
        migrations.CreateModel(
            name='CollectionSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_series', to='catalog.collection')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_series', to='catalog.series')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('collection', 'series')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='collections', through='catalog.CollectionSeries', through_fields=('collection', 'series'), to='catalog.series'),
        ),
    ]
