# Generated by Django 5.2.16 on 2026-07-14 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('preferred_language', models.CharField(blank=True, default='fa', max_length=10)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='public', max_length=20, verbose_name='Profile Visibility')),
                ('watchlist_visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='private', max_length=20, verbose_name='Watchlist Visibility')),
                ('activity_visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='followers_only', max_length=20, verbose_name='Activity Visibility')),
                ('ratings_visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='public', max_length=20, verbose_name='Ratings Visibility')),
                ('followers_visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='public', max_length=20, verbose_name='Followers Visibility')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='Show Online Status')),
                ('allow_follow_requests', models.BooleanField(default=True, verbose_name='Allow Follow Requests')),
                ('allow_dm', models.BooleanField(default=False, verbose_name='Allow Direct Messages')),
                ('is_private_account', models.BooleanField(default=False, verbose_name='Private Account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Privacy Setting',
                'verbose_name_plural': 'User Privacy Settings',
            },
        ),
    ]
